Feat/front-end
erotourtes/8080folio pull request #9
Opened 2024-05-31 08:25 UTC by KseniiaHorai

Implement front-end for the project

2024-06-02 19:52 UTC, erotourtes requested changes

2024-06-02 19:52 UTC, erotourtes commented on src/routes/auth/user/components/Header.svelte
> +    { name: 'Blog', link: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' },
:dancers:

2024-06-02 19:52 UTC, erotourtes commented on src/routes/auth/user/components/Main.svelte
> +  console.log('repoArray', repos[0].html_url);
I am not sure if `vite` removes console logs in the production build, but it's better not to bloat code with them

2024-06-02 19:52 UTC, erotourtes commented on src/routes/auth/user/+page.svelte
> +  }
There should be these types in /src/lib/types/types.ts, or if they differ it's better to move them there

2024-06-02 19:52 UTC, erotourtes commented on src/routes/(authed)/layout.server.test.ts
it might have got here from another branch

2024-06-02 19:52 UTC, erotourtes commented on src/app.html
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
Do you use these fonts? It is better to add them to the tailwind config or remove otherwise

2024-06-02 19:52 UTC, erotourtes commented on src/routes/auth/user/+layout.svelte
> +  import Header from './components/Header.svelte';
I can't notize `Main` and `Footer` components, does `vite` allow to compile with unused elements?

2024-06-03 13:44 UTC, andriihalai approved these changes

2024-06-03 15:47 UTC, erotourtes approved these changes

2024-06-03 15:47 UTC, merged